### ISSUE TITLE
Problem with example code

### ISSUE THREAD

**Issue by tMAE1989** [jmschrei/pomegranate#541]
Hello Guys,

I have an issue with pomegranate. I installed pomegranate package in anaconda and tried it also from github but I receive always the same issue when I am executing one of the example codes on the documentation. Also all other usecases do not work. I hope you can help me.

This is the executing code:
`from pomegranate import *
from pomegranate.utils import plot_networkx
import time
import matplotlib as mlp
import matplotlib.pyplot as plt
import numpy
import networkx

numpy.random.seed(6)

X = numpy.random.randint(2, size=(200, 15))

X[:,1] = X[:,7]
X[:,12] = 1 - X[:,7]

X[:,5] = X[:,3]

X[:,13] = X[:,11]
X[:,14] = X[:,11]

a = networkx.DiGraph()
b = tuple((0, 1, 2, 3, 4))
c = tuple((5, 6, 7, 8, 9))
d = tuple((10, 11, 12, 13, 14))

a.add_edge(b, c)
a.add_edge(c, d)
print("Constraint Graph")
plot_networkx(a)
plt.show()

print("Learned Bayesian Network")

tic = time.time()
model = BayesianNetwork.from_samples(X, algorithm='exact', constraint_graph=a)

plt.figure(figsize=(16, 8))
model.plot()
plt.show()
print("pomegranate time: ", time.time() - tic, model.structure)`

The issue is following in utils.pyx:
`Exception has occurred: AttributeError
'NoneType' object has no attribute 'AGraph'
  File "D:\Python\pomegranate\utils.pyx", line 291, in pomegranate.utils.plot_networkx
    q[2] = -1.01515636749021914166146E+3
  File "D:\Python\python code\BN2.py", line 29, in <module>
    plot_networkx(a)`

If I outcomment the line 29, i will receive an different error in BayesianNetwork.pyx
`Exception has occurred: ValueError
must have pygraphviz installed for visualization
  File "D:\Python\pomegranate\bayesiannetwork.pyx", line 281, in pomegranate.BayesianNetwork.BayesianNetwork.plot
  File "D:\Python\python code\BN2.py", line 38, in <module>
    model.plot()`

I hope you can help me with that!
(Iam a python beginner and need this library for going into Bayes Nets)

**Comment by XJSilver** [comment]
Hi, I have a similar problem with displaying the png:

Python 3.6.7 (default, Feb 28 2019, 07:28:18) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.5.0 -- An enhanced Interactive Python.

runfile('E:/X/SpyderFiles/pomegranate bayensian networks.py', wdir='E:/X/SpyderFiles')
Traceback (most recent call last):

  File "<ipython-input-1-2bbacd1b41d5>", line 1, in <module>
    runfile('E:/X/SpyderFiles/pomegranate bayensian networks.py', wdir='E:/X/SpyderFiles')

  File "C:\Users\X\.conda\envs\mygreatenvironment\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\X\.conda\envs\mygreatenvironment\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/X/SpyderFiles/pomegranate bayensian networks.py", line 24, in <module>
    model.plot()

  File "pomegranate\BayesianNetwork.pyx", line 272, in pomegranate.BayesianNetwork.BayesianNetwork.plot

  File "pomegranate\BayesianNetwork.pyx", line 273, in pomegranate.BayesianNetwork.BayesianNetwork.plot

  File "C:\Users\X\.conda\envs\mygreatenvironment\lib\site-packages\pygraphviz\agraph.py", line 1515, in draw
    data = self._run_prog(prog, args)

  File "C:\Users\X\.conda\envs\mygreatenvironment\lib\site-packages\pygraphviz\agraph.py", line 1364, in _run_prog
    raise IOError(b"".join(errors).decode(self.encoding))

OSError: Format: "png" not recognized. Use one of:

**Comment by jmschrei** [comment]
I think that downloading pygraphviz should solve the problem. You can get it using `pip install pygraphviz`. The code initially fails for me but runs after I download it.

**Comment by 5aurabhpathak** [comment]
There are a lot of issues with trying to install pygrahviz specially on python3.x versions. See [here](https://github.com/pygraphviz/pygraphviz/issues/16) and [here](https://github.com/pygraphviz/pygraphviz/issues/74).

Even after applying the patch mentioned in one of these issues the problem is not solved. To think, both these issues are more than 4 years old and nobody has addressed it on pygraphviz

**Comment by MaheshGithub76** [comment]
I'm running into the same error as @XJSilver 

OSError: Format: "png" not recognized. Use one of:

Any updates on this issue?

Thanks
