### ISSUE TITLE
Exception OverflowError: (34, 'Numerical result out of range') in 'pomegranate.hmm.HiddenMarkovModel._baum_welch_update' ignored

### ISSUE THREAD

**Issue by Narsail** [jmschrei/pomegranate#57]
When i use a version prior the mentioned one, everything works fine while getting some ZeroDivisionErrors through the training. 
<img width="360" alt="screen shot 2015-12-30 at 23 11 10 2" src="https://cloud.githubusercontent.com/assets/7859096/12058309/fafe1f74-af4a-11e5-88ba-0f07b9539138.png">
After updating to the newest version, the output looks like follows:
<img width="360" alt="screen shot 2015-12-30 at 23 09 01 2" src="https://cloud.githubusercontent.com/assets/7859096/12058314/0de39ace-af4b-11e5-8c9b-97274c6110e8.png">
You can see the difference with the first Training for a "Jump". The funny part is, that every training with the broken version seems to be different. It is like having a random factor messing something up.

In my system i use Feature Vectors with 25 features and i use a IndependentComponentDistribution with 25 NormalDistributions. (Maybe the problem lies here?) The states of a HMM are aligned at the average length of a Feature Vector chain of the training dataset.

**Comment by jmschrei** [comment]
It would be useful if you could paste a minimal code/data example which reproduces this error, or at least your current code. To use Independent Components Distribution you need to give it a list of tuples, or a list of 2d numpy arrays. To be honest I've never seen that error before though. Are you using a lot of really big numbers?

**Comment by jmschrei** [comment]
In that commit I fixed an issue where IndependentComponentDistribution didn't actually update the emission distribution, so it may have worked, but it was not properly training. I'm guessing that this issue is related to updating the emission, as opposed to the transitions.

**Comment by Narsail** [comment]
Actually those numbers are really small. So basically they are big in terms of the used precision. I will try to dive deeper into it in the next days.

**Comment by jmschrei** [comment]
Okay. If you post the code (or a minimal reproducible example) I may be able to help.

**Comment by Narsail** [comment]
Okay, i used your newest version and the Multivariate Gaussian Distribution but still get only NaN as a output. Maybe i got lucky that it worked with the broken IndependentComponent Dist :D With the current code i don't get any errors/warnings though, maybe i forgot a flag or something.

Anyway, i prepared a code snippet with trainingssamples and a sample code for you. Sry for the unorganised sample structure, but this was the fastest way to give you access to it. My system works normally with a direct mySQL access and no file. And i'm really struggling with the problem, maybe i forgot something fundamental, maybe you can help me. 
```
from pomegranate import *

import numpy as np

def __genMultiGaussianDistWithCovMatrix(index):

        numberOfFeatures = 25

        mu = np.zeros(numberOfFeatures)

        # Generating a Multivariate Gaussian Distribution for every Feature component

        sumForAvg = 0

        # print('Number of Samples: {0}'.format(len(self.featureVectorChains)))

        # Estimate mean vector
        for featureVectorChain in trainingsSet:

            # print('Length of Feature Vector Chain: {0}.'.format(len(featureVectorChain)))

            mu = mu + np.asarray(featureVectorChain[index])
            sumForAvg += 1

        mu = mu / sumForAvg

        # Estimate Covariance Matrix

        cov = np.zeros((numberOfFeatures, numberOfFeatures))

        sumForAvg = 0

        for featureVectorChain in trainingsSet:

            x = np.asarray(featureVectorChain[index])
            var = np.matrix(x-mu)
            cov += np.transpose(var)*var

            sumForAvg += 1

        cov = cov / sumForAvg

        print(cov)

        return MultivariateGaussianDistribution(mu, cov)

# A sample represents a chain of featurevectors (25 features each)

sample1 = [[0.0022352917605754337, -0.001917509347132827, -0.0017275794733814507, -0.001321292675288938, -0.001942215770180415, -0.002851757302567399, -0.002117319771736926, -0.0003683551354793315, -0.0021368219040912885, 0.0004983477106264617, -0.0018678886140903422, -0.002115848260751826, -0.002333265469311074, -0.0027643627777322014, -0.0010279721161253223, -0.0022098404732182456, -0.001000115871532001, -0.002683121678630408, -0.0017072532709875043, -0.0015899143369600157, -0.0019150306474648997, 0.042812789107397754, 0.018407668704281954, -0.0013781993453707397, -0.000949634524451906], [0.012208688930300877, 0.0007374025152098131, 0.0007531347845490354, 0.0004488692592034355, 0.003152591721899046, -0.0008833640099654065, 0.0004977518282305493, -0.0028588998722799902, 0.003315399991679861, 0.0030838938640760333, 0.0045933720110699645, 0.0029118219573139184, 0.0012405354185854283, 0.0022737263454004567, 0.0017690562777387907, 0.0010134050498817329, 0.0018356459357781896, 0.0022977899243532794, 0.00335590920747258, -0.0015980371685552536, -0.000791614277205806, -0.03741167119355062, 0.07249670135740999, -0.01754917149937682, 0.0011232569251524538], [0.017082168783194376, 0.0009357392388925361, 0.001965330664355024, 0.0012232413154363018, 0.0026748612455525975, -0.001428373876788575, 0.0006276750562946832, -0.0020649189937504138, 0.0052301938279822125, 0.0022596267163869817, 0.006631293208908419, 0.005653986640858093, 0.004855622566937754, 0.004091077392950558, 0.0027045344336588785, 0.0034447900298870686, 0.0027840786481348567, 0.004530280181018044, 0.0012350110611622236, 0.0038238898474811578, 0.0029066823287384816, -0.03218769377335572, 0.007313932806267172, 0.0007796133102788784, 0.002285811473840461], [-0.0025718470825550344, 0.004345647067987558, -0.0029232741464266937, 0.0051456920232581405, 0.0052074358131068, 0.0059175074988513, 0.0009412835634770555, 0.002057506530892933, 0.003214419255335419, -0.0020200480473821993, -0.0014472260104520973, 0.004546483279975595, 0.012735130271539576, -0.0012276283056848164, 0.002989917448532711, 0.0051368439300287175, 0.0030734136637569987, 0.005487183557146297, 0.005443519352272221, 0.008932089104344216, 0.005745268363671998, -0.02879783956612463, -0.08256783043543264, 0.026171000584604903, 0.001747100141377772], [-0.007942093140735643, 0.004800041963439515, -0.0018199742532228795, 0.003693910093774291, 0.006420052485257112, 0.007093112666225684, -0.000709362950539588, 0.0016280069046113925, 0.0018562572575849987, -0.0015741652289644116, -0.001595622870087599, 0.003996361095604257, 0.004958829200013649, 0.0023943128015280367, 0.001006984843334971, 0.003888642761807442, 0.0010630212914001834, 0.004602594739846809, 0.008168715838322039, 0.006777452879521207, 0.003989063481914317, -0.025190199169044275, -0.07713080401788172, 0.031176661279123816, 0.001131472350384346], [0.017433628484785666, 0.0058468725068982685, 0.002052750334702866, -0.0007433041932969329, 0.006820023421653511, 0.011638224454345428, 0.009954675101747247, -0.002808840291152908, 0.003388424018731282, 0.0030319247685147576, 0.00412630570288095, 0.0031529748606919867, 0.0004324245784711179, 0.0052553859673591516, 0.003985941476833305, 0.007897585581281551, 0.004083230691290288, 0.00857017753202817, 0.007282332205769097, 0.006285614378809191, 0.005082495575835854, -0.006252953177541105, 0.023828100937092506, -0.022400731738650394, 0.002848393139929523], [0.013724914115585518, 0.005217713619114898, 0.0011302702150707954, 0.0026043171745754284, 0.004115101895755641, 0.01063149764102576, 0.007743619409711885, -0.002391497187408155, 0.003362651044790739, 0.002598662181173281, 0.005577735087762349, 0.00021032373182073744, 0.002152842812353106, 0.0006393709312205395, 0.00495158762322343, 0.007499064587899905, 0.005062249162220553, 0.008522896616076775, 0.0074674731576257255, 0.0026938315065019114, 0.005950159342698824, -0.013544395906054364, 0.023087902314638583, -0.02382847226115728, 0.002110169668780789], [-0.0031592507283022715, -0.0011905683233781675, -0.0030096255991027246, -0.001442790341916714, -0.0022014519930329116, -0.0012512249062368282, 0.001772402864817004, 0.00019812097318250898, -9.662770818603241e-05, -8.973653541409981e-05, 0.0004135438774463804, -0.0007300681601501736, 0.00039428094772024327, -5.926754659623771e-05, -0.0005203584051663886, -0.0011882361477883162, -0.0004854726960954807, -0.002539203429911818, 0.0014813018426842921, -0.0028051864791687115, 4.397207881952741e-05, -0.013566476019582031, 0.02036384639277334, -0.010347469453217847, -0.0009141947578473774], [-0.0017118192544172029, -0.0012764074137648733, -0.0027093567360226677, -0.0024655447660524295, -0.0008886477735524224, -0.0012988222507381245, 0.0014588369776127508, -0.0012132504219002972, -0.0011506287519566893, 0.0013754713878664931, -0.0019475555719856066, -0.0010597597771080586, -0.0007637431848710672, -0.0006413216249240775, -0.000840374204871161, -0.0012419593118058211, -0.0008099200933866178, -0.0020471330006171344, -0.0013965665163677024, 0.0005252730246541026, -0.0016239656265112474, -0.023572192513346458, 0.0072798015711942965, -0.014461248798376338, -0.00048815849470947606], [-0.0002850557954131533, -0.0016515969133820375, -0.00249147936936487, -0.0019353002866807393, -0.0015296060309315186, -0.0017211287498703396, -0.0022485033548120654, -0.0010549835719920189, -0.002694093053843154, 0.00036103191410191845, -0.002789706639551548, -0.0026126426956668753, -0.0028291928800024744, -0.0028956236150577065, -0.001568291210329294, -0.0019771364003762486, -0.0018462354703999433, -0.0025948144455080046, -0.0009013644449586308, -0.001963588415551331, -0.002347692838523541, -0.03403941030127554, -0.09632440142553061, 0.027010957601427885, -0.0011448352468604128]]
sample2 = [[0.0032526227290120687, -0.0015254669372523262, -0.0014745355611129425, -0.0007781903618871951, -0.0018432537799936016, -0.002178714830804251, -0.0011225289015086228, -0.00020794294208125835, -0.0020421549247908568, 0.0003318166206691742, -0.0016995132931131526, -0.002522694964035327, -0.002333231414071415, -0.002155985709382879, -0.0006308278583135211, -0.002097135200109016, -0.0005974719367168111, -0.0021366752180796353, -0.0014168319925878649, -0.0018323686504504847, -0.0023447711690997553, 0.035501695706738494, 0.07748068078036083, 0.012689021620987378, -0.0009384617454106819], [0.012305893354489564, 0.00012098520307774217, 0.0007773127448683918, -0.000657508438142626, 0.002002569753189514, -0.0013264068050509146, 0.0019974006056018906, -0.0031144262826059434, 0.0028388190493274876, 0.0033491672870187357, 0.004889482394658651, 0.0016189066728271085, -0.0014508479266260913, 0.0026252008313384988, 0.0019206017088698305, 0.0007977669134865064, 0.001989289976938623, 0.001340857495704841, 0.002256302294401581, -0.0017334543982084419, -0.0007419500367196794, -0.03131916444061388, 0.06009562921670692, -0.01490634859907838, 0.001186054080553521], [0.01648376942835984, 0.0007154658104463837, 0.0018164889220467397, 0.0009702003922362108, 0.0012154359661012235, -0.00018546092774241528, 0.00328732923560102, -0.0022127271247575093, 0.0044306640236551655, 0.002413072964080124, 0.005989332283885067, 0.0042245642741882625, 0.005238115008420488, 0.002013984819564218, 0.002697160212085712, 0.0032593532112776442, 0.002776602307908314, 0.0038939319936876927, -6.229390734984002e-05, 0.0019049018744724446, 0.003046614212993398, -0.02845337340362528, 0.0008069724485751174, 0.002665234903564733, 0.0020972546671451163], [-0.002875699382651314, 0.003713621209109965, -0.002998852278965314, 0.004908526025235473, 0.00649748301399055, 0.002273354278954909, -0.0013002365303782153, 0.0023158674714837237, 0.0015273977785070494, -0.002288264123277406, -0.0019297676170342613, 0.002220009518254942, 0.006961161532624979, 0.003558180407020358, 0.00046485501019005536, 0.00413783388618971, 0.0005133840124907845, 0.0018875101820843257, 0.006433796222235824, 0.006966916747888788, 0.00636526629304085, -0.02963708545599361, -0.05227881877847429, 0.02644921222971091, 0.0008818233138142894], [-0.012119791161690553, 0.0035719914438800417, -0.0007808423637028191, 0.003965142965815676, 0.0037047108195606975, 0.005292108371207994, -0.000158611794564237, 0.0006164643921914245, 0.0026394270236778216, -0.0005240375948798777, 0.0012254230800588903, 0.004200336859119428, -0.000998529407638923, 0.00493064765263306, 0.0007671502230814659, 0.004728140595279406, 0.0008198654272417755, 0.0001214260785852836, 0.0011143913999552171, 0.009870971441204416, 0.007517203136320564, -0.0032728127906071045, -0.03936240064649624, -0.0016799565904932724, 0.0008885147880326244], [0.011129267611557503, 0.005061045648948594, 0.0004846469453352155, -0.00100805627474831, 0.00792791075078522, 0.009377958096487563, 0.004265513965776649, -0.002591532804527924, 0.0029106809775765853, 0.002806328123790045, 0.004332565780010252, 0.0006637634246730328, 8.946392145333693e-05, 0.0031707978429488157, 0.003594499657130706, 0.004691154701201937, 0.0036863681622820972, 0.006490846109968373, 0.0055963466111998515, 0.0034839806532564305, 0.001175031590844304, -0.00011979585878455734, 0.0348214464874677, -0.02132190703881535, 0.0020810100837608935], [0.014660151858811551, 0.004076162069678463, 0.001362894822784019, 0.0023047488629282836, 0.005643145066310706, 0.007736740377332006, 0.0014918303707158883, -0.0017211567457164356, 0.0015566509544594192, 0.001902751714315268, 0.003316757948376559, -0.0013362059641562989, 0.0003104939025616972, -0.0010643466701556153, 0.0025238449997051996, 0.00220530880218532, 0.0026008870162892938, 0.0031033071802248047, 0.005379158516527721, 6.248718586024124e-08, 0.0029105876882337847, -0.02148723262591041, 0.05271737409101801, -0.02243657338040566, 0.001264663659895917], [0.0013817716690910408, -0.001386439859841041, -0.001939878194102482, -0.001787997382106348, -0.000758801925434575, -0.0013457372193091306, -0.0011493314006838708, -0.0001801017185372899, -0.0010253441919971513, 0.00030291339826253437, -0.0007225444208180882, -0.0008961583605223833, -0.000979843108861804, -0.002175615778974696, -0.0008646397654542745, -0.0018911854731155236, -0.0008345216848776145, -0.0020249886661582177, -0.0010650373920925182, -0.0005187967976077269, -0.0025469333867980766, -0.005599802443032235, -0.054021972217452835, 0.027996462568251217, -0.000812241619421096], [-0.0026469935947013848, -0.002318961819770796, -0.002980980642142459, -0.002370795999693621, -0.002503643671781596, -0.0029920996738979975, -0.0029368398411226226, -0.0010571032726802757, -0.0025198256816314746, -0.0004877833131753558, -0.0026316207206556062, -0.0028765274735450615, -0.002538439849762897, -0.002900075045132372, -0.0014081090322597318, -0.0023583871937225033, -0.002047113370351977, -0.0029506245162611586, -0.0018755016750677486, -0.0027962498805962173, -0.0023237402864312155, 0.02366322851979186, -0.009877027557256056, -0.006405323413385392, -0.0016586475846678429]]
sample3 = [[0.0018142852006357909, -0.0020174929784674226, -0.0018322977512311323, -0.0014913653612792172, -0.0025063816314766763, -0.0024255263243376057, -0.0017046435810166378, -0.0003100119245906495, -0.002160808627245277, 0.000437779007617774, -0.0018011660042473953, -0.002346188727946363, -0.0029809642649443737, -0.002865563907138186, -0.0005084174598882044, -0.0017642134425181217, -0.0004733663919058849, -0.0011696430404509836, -0.0006460362725052009, -0.0019506285684755707, -0.0016839888014152204, 0.04379627747172537, 0.09014434368295197, 0.025193453577175177, -0.0009402409429543275], [0.013000444010908349, 0.0007356478767368028, 0.0009500705010182448, 0.0009254331673372929, 0.002127198792438082, -0.0009627372940948562, 0.001914588203831881, -0.0033228895419624947, 0.003547865264339293, 0.003565582342890118, 0.0054366251452511215, 0.0024421337535994437, -0.000834145999921326, 0.004117629902561763, 0.00260242280561526, 0.001533600617649138, 0.002680552972269864, 0.0023019169477468413, 0.005119456246746285, -0.001788189702070016, -0.00021859737214523163, -0.0345216868397996, 0.07420971240502838, -0.016311254161336244, 0.0014845264342267538], [0.01708877674117151, 0.0015688171595573616, 0.001966974282401183, 0.0014942858618086524, 0.002663583894654677, -0.001343960174292551, 0.007397274561540755, -0.00221347977225441, 0.005505746579959697, 0.0024138543211911856, 0.00656668271127165, 0.006454995372474417, 0.006226036335777661, 0.003013588867238777, 0.0037068626415388472, 0.004172573866511123, 0.0038002871558965316, 0.004868688613033079, 0.0004948001377404984, 0.0063840840882575, 0.006558096160570208, -0.02725818926059205, -0.014867563043633082, 0.005220617765484254, 0.002745374751693058], [-0.0025237300679018283, 0.0034695917240466527, -0.0029113058509434263, 0.004795475643617531, 0.003110201936110966, 0.005065653792933838, -0.00049404744322333, 0.0024412426125740364, 0.0018035278432200293, -0.0024184216783674113, -0.0015708545601696962, 0.003921111022698224, 0.0047123687933316805, 0.005066144945174488, 0.0003790231636826197, 0.004186420577302801, 0.00042636356153267325, 0.0021316946803892475, 0.004417144652145129, 0.010699933360961643, 0.005767731384302501, -0.020978324620706115, -0.055847022655787455, 0.028771801876451664, 0.0009966850380413513], [-0.00946709493214272, 0.003255197845662603, -0.0014406557900219184, 0.0035393648560799276, 0.0016991470999804166, 0.0058626594016628515, 0.000980884331647569, 0.0008061339172126455, 0.0027106561393450326, -0.0007209420325312127, 0.0009007710162255222, 0.004440349817161294, 0.0028157434069301882, 0.0055286681549902945, 2.8220373973738463e-06, 0.004040711808104752, 4.4952779959246155e-05, -0.0012635210522536227, 0.001131190034641192, 0.006567052745932919, 0.003902847195016954, 0.0008370487583759951, -0.022632041575129744, -0.009694635863668024, 0.0005904458593703499], [0.01141447214800797, 0.00449154858507099, 0.0005555867613235737, -0.00044418085366087926, 0.002696361308257907, 0.008598617524259888, 0.01304720833234864, -0.002273446860458162, 0.0033066077059400244, 0.0024761088440462754, 0.005103729463727134, 0.0012541963705143006, 0.002109865898587363, 0.0010651840397063084, 0.00320706348264374, 0.004539736291740865, 0.0032935667488997056, 0.006632101921104366, 0.007244697608328975, 0.0021496508806729533, 0.004835011103900695, -0.00460299047472165, 0.03692744680625331, -0.019998390695112615, 0.0017162369386755547], [0.012047451560836284, 0.003914920991064694, 0.0007130297095645375, 0.001345129209666038, 0.0008242424452809308, 0.008870322041352297, 0.008365080275061217, -0.001775709721211673, 0.0013334732713781029, 0.0019593856040289424, 0.002606164080129045, -0.0007996047628096029, 0.002685766023172402, 0.0023968542767841823, 0.0021414708062749157, 0.0022144205453333956, 0.0022132176825745077, 0.00340875837179854, 0.005385759772522212, -0.0008559066137667666, 0.0022647365942444863, -0.02977746694021824, 0.05109790454845102, -0.01865601715826837, 0.0010078060592863935], [0.0012977009526177953, -0.0007730266596284518, -0.0019607893662417692, -0.0019170681847524827, 0.00018824249693040834, 0.0001974529988776902, -0.0006479741949020498, -0.0002940763619323087, -0.0012043002499176067, 0.00042123558556013353, -0.001457359790256532, -0.000877543220524385, -0.00024790376597996067, -0.0014253401211309707, -0.000718284220881263, -0.002019923569544011, -0.0006861394001290272, -0.0023964794189016247, -0.002230283536672342, -0.0016954518965235585, -0.0013707924373238798, -0.024692319332275146, 0.016446336709863275, 0.009118087986023402, -0.0007873631294249176], [0.0004903896836017442, -0.002338291994289874, -0.0025127579514004524, -0.0027535004173059176, -0.00226570251832707, -0.0026819832936222257, -0.0028455547393244694, -0.0008932370842552887, -0.0027186606237002997, -0.0005898534154069495, -0.0028984038926711093, -0.0028470501830027656, -0.0025926780871146425, -0.00286533227694396, -0.001053452453630185, -0.002674546450191972, -0.0018313726400979893, -0.0028781986000257992, -0.0028931862642048818, -0.0027376358686415116, -0.002869200022943011, -0.0007186413875118646, -0.008868852560193145, -0.013261704038879926, -0.0016943879440384447]]
sample4 = [[0.0002112270241309691, -0.001601513714099929, -0.0022310314231257043, -0.0015381629481469809, -0.00225879352984895, -0.0016517493042091393, -0.000943702102558829, 0.0002179862847529158, -0.001770156303218072, -0.00011035960600544524, -0.0015674767545954347, -0.0022612909438784164, -0.0010651888592443852, -0.0016122841010737458, -0.0005590126374914706, -0.0005253003037100821, -0.0005246622144996647, -0.001864895372323269, -0.0024538431660165653, -0.0010079808827930037, -0.0004759866247912873, 0.00012181920977463829, 0.04147521139290722, 0.001962381669753988, -0.0010182852035231632], [0.015573175260573986, 0.0006261292538186902, 0.0015899939878961428, 0.002065856203397853, -0.0007753836971767942, 8.373559214150525e-05, 0.0022082221182454427, -0.0024807090568557647, 0.0047578540452469465, 0.0026912770226109888, 0.006018883026465206, 0.004891168252017966, 0.0021587635205516957, 0.007445096834867591, 0.003906321259678198, 0.0036483191414102586, 0.004002507888692539, 0.002274048050534333, 0.0006093928648205784, 0.0037573685709973966, 0.0030643344159476033, -0.024390516149589894, 0.01208483159288779, 0.006423898157094336, 0.0020555502251197078], [0.01968813618744884, 7.980970601199693e-05, 0.002613521083870233, 0.0003280245317711914, 0.00014141540309229648, -0.00012705327630645484, 0.0023240892923459227, -0.0026449268087847884, 0.005042167359896369, 0.0028617588334993384, 0.006516420262661797, 0.004805895016123867, 0.005382733439290245, 0.006184803165299119, 0.001780888772909112, 0.004867170867458076, 0.0018476422880364604, 0.005550668963985457, -0.0015033250659296068, 0.010392824475635479, 0.0031222750590634302, -0.024006901461200176, 0.007129193511185622, 0.007002121170774732, 0.002606967693867722], [-0.006744433877040765, 0.0033083326969193375, -0.0021178717861326415, 0.004221720991537319, 0.005688369370881649, 0.0026254276530626097, 0.0033555327076592464, 0.001982359467068406, 0.0004177740750525246, -0.0019420345112494868, -0.0015432142806095287, 0.0004153358109832526, 0.0039056043849339745, 0.0016197455595829803, -0.0011694032059419704, 0.002811529964467744, -0.0011435055073855847, 0.0004921616536970391, 0.0033334568190868615, 0.008722997809029177, 0.002803701330274746, -0.028195527629834422, -0.07823252364937226, 0.03241445467753551, 0.0002892108257849251], [0.0034724800701895326, 0.007350338814710292, -0.0014198497573002548, 0.0031271170825380363, 0.009371296374405785, 0.013302102922895437, 0.008042484648693303, -0.0011152916677606367, 0.004612391291106865, 0.0012737760132682972, 0.004059273994968523, 0.005823431273928679, 0.004584885305942296, 0.0016810125003917874, 0.004728036600291593, 0.006214759964449729, 0.0048356023915957355, 0.00924322775209161, 0.0056082063303440404, 0.008943806722973083, 0.005964350045592913, -0.02027814157869887, 0.008864528899891071, -0.007638625422162949, 0.0026258527766036964], [0.012489255649347572, 0.005924210842690657, 0.0008229210217153111, 0.00046868066289325463, 0.0038483513531603992, 0.013013580559578164, 0.010224337500422941, -0.0023254814209729083, 0.0038450490939245306, 0.002530128254256978, 0.005181883873172745, 0.0013384573564100592, 0.0030337137684038774, 0.0016760167090079077, 0.004297107071027133, 0.005733930007301529, 0.004398705324904861, 0.008812098350219132, 0.007978329768671594, 0.0067479996719606, 0.006179640337535189, -0.008590268542415224, 0.021767034076908297, -0.0145904321895876, 0.0022138004694354984], [-0.002182803994965407, 0.0012193490735623112, -0.002826506242982269, -0.0003740419978688375, 0.0029696106892429237, 0.0025135896808831755, 0.0010946395277037408, -0.00017920469998293904, -0.000722483182129367, 0.000301982163083939, 0.00015666919960513297, -0.0017974224783552698, -0.0008761053045525601, -0.0009488205597862122, 0.0003314158716044145, -0.0003693279549065412, 0.00037809700087816097, -4.909327648490095e-06, 0.001518632784958945, 0.000399962626130389, 2.79082554700937e-05, 0.01055125329166697, -0.07562843035127441, -0.01706213610615038, -0.0003621019082489645], [0.0003393138628485329, -0.0013240407507385317, -0.002199171983292662, -0.0018903273300446735, -0.0011953306956020925, -0.0012971376677972915, 0.001233790597016441, -0.0009521708439989433, -0.0017807633015070818, 0.0011044329726906125, -0.0021389095764366016, -0.001538582421834337, -0.0007444423162236714, -0.0020823580904350907, -0.0005272299794988227, -0.0021236857789556692, -0.0004924394283927849, -0.002358794715481243, -0.002466114860834549, -0.0028406337837398195, -0.001656704507725405, -0.019282982692090334, -0.010492949898460863, -0.006833846115391965, -0.000622231328581216], [-0.0007601909199811102, -0.001829530471647356, -0.0026993944453375346, -0.002188716048360789, -0.002251650427961225, -0.0021849234472095503, -0.002426213867394866, -0.0008595254868163853, -0.002592199216594691, -0.0006108519278520863, -0.0029602713171652854, -0.0028100829256007555, -0.0023244579636167505, -0.002748559233555412, -0.0007885332964711827, -0.002188865994300677, -0.001670219976175593, -0.002875337465170541, -0.0021219099509754663, -0.001833581038741196, -0.0027152730006988444, -0.014388475195070397, -0.0952482857772573, 0.023771997889586234, -0.0016636658745050428]]
sample5 = [[0.0003387315869579159, -0.00150330257463344, -0.002199316814595308, -0.0011421295416095421, -0.0013993396094606398, -0.00146829918427694, -0.0015829172855289608, 8.103162585607232e-05, -0.0018107969452610887, 3.181916568070875e-05, -0.0013618670354330748, -0.0024474899972795256, -0.0017131019434463255, -0.0020690017063618596, -0.0006419838161113026, -0.0018818072700627637, -0.0006087823828732798, -0.0019336609614227646, -0.0010920853424990528, -0.0015212073152804661, -0.001704298882716904, 0.03153331543737843, 0.05474201702494992, 0.010624763009094703, -0.0010793963736099059], [0.015842726724972653, 0.0009965019274192335, 0.0016570403663367414, 0.0018189933778334198, 0.0015923584653376168, 0.0009480075554800816, 0.0010505256288689366, -0.002513251172982299, 0.003887547593674158, 0.002725060452369474, 0.005539292900397704, 0.002498689983608819, 0.0030000533723793976, 0.002819091068858398, 0.0034417785690126863, 0.0014796821482968609, 0.0035315321835676905, 0.002200804371461949, 0.002337097774461022, -0.00030186647707881094, 0.00022183211087342731, -0.01982732281099208, 0.052757369967898364, -0.0053476507664112485, 0.0016276536264063842], [0.01809944885525061, 0.000523934234911411, 0.0022183619170077166, 0.0015092796667838077, -9.766201678189653e-05, -3.429327525003918e-05, 0.001923059763109851, -0.0021987414615760583, 0.004576781426798004, 0.0023985538200920918, 0.005105129944126343, 0.005632894668722673, 0.0036169321994012093, 0.004196494272849422, 0.0018984438468988153, 0.0038115230309982155, 0.001966825271593873, 0.006016702237631621, 0.0006375719663172297, 0.006382454299041, 0.005625582857950857, -0.02049671471763961, 0.04129196276067734, 0.000571358456973776, 0.002168187154289623], [-0.00521124064243054, 0.004568697847616366, -0.0024992277326104906, 0.005308440395216575, 0.007813060144327538, 0.00336534422199074, 0.004880116719364367, 0.0018497148002196314, 0.0006501776408652342, -0.0018043301355445106, -0.0017737404977418766, 0.0022549502957738316, 0.0005763129106662978, 0.0012279602044140742, 0.0003143885911697276, 0.0031890784228466337, 0.0003608339256641339, 0.00220685322232157, 0.0056160134063240885, 0.008609063237006737, 0.003064019732699408, -0.022389708313906263, -0.06712713963915636, 0.030115614371118905, 0.0007965661828836392], [0.0004466017833765132, 0.00796918999882636, -0.0021724859234047256, 0.0026203729559641648, 0.016357097136677393, 0.008563825571134737, 0.0021869037008857, -0.0013231962267607137, 0.003734075920111315, 0.0014896110572506058, 0.0027581258496784285, 0.005316814118952573, 0.0011105717379782344, 0.007747863990342028, 0.00624857092584708, 0.004952172069900956, 0.006377193165780736, 0.008054376124180284, 0.006073215699076339, 0.010911613389762688, 0.002933813827990951, -0.02100761254051734, 0.02453876220642485, -0.01281945050169281, 0.0030940606330848146], [0.0067245884873470725, 0.005851530365101098, -0.0006109426636102769, 0.00140691194879937, 0.0065056189820678735, 0.012419529407595853, 0.004051171967571201, -0.0016687085855758778, 0.003510647148227471, 0.0018483029277895037, 0.005237438655538007, -0.00021004224367191602, 0.0024610366774451245, 0.004439260037580023, 0.004938562925150981, 0.004959332186855836, 0.005049044097364359, 0.008871272484303323, 0.009368988798346606, 0.006114121759209591, 0.005366113321608267, -0.0105475483804491, 0.04873762871055325, -0.021885831118502168, 0.0022352789557137744], [0.001203070438516347, 0.0016980249076319813, -0.0019843271098582927, -0.0010461586514237307, 0.00015404075481347752, 0.00547805250279492, 0.004233970466473715, -8.275040692483699e-05, 0.00013070368841026916, 0.0002018486369861765, 8.107217689701296e-05, 0.001299555619447782, -0.0006826671650476826, -0.00055634395391153, 0.0005582168701458431, -6.055378843619414e-05, 0.0006080387529656597, -0.0018705526145754569, 0.0025159252805809036, 0.000595667288261047, 0.0013544171682715789, -0.004669670965156062, -0.08889068315995191, -0.002117305058882703, 4.9968086966779976e-05], [0.002569118119616395, -0.0005330078325734795, -0.0016445457994533992, -0.0014832246613196314, -0.0017933848356200524, 0.0013462287363749494, 0.0013205651494471384, -0.001238260284045958, -0.0014602169368195515, 0.0014014352470630503, -0.001980119034617927, -0.001743480933902516, -0.0009871148151465669, 0.00046033461345488185, -0.0004016283574058639, -0.001940293601688459, -0.00036509846766147075, -0.0024680839923771963, -0.002009994304914679, -0.0027610338024082375, -0.001726454413654896, -0.029550225219420075, -0.009731256807629185, 0.009720318649230588, -0.0003515393625187696], [-0.0019901099394538115, -0.001788189308563412, -0.0028829474070285097, -0.002117782404191551, -0.0019593621785730874, -0.0024812785362033503, -0.0025681648159473977, -0.0009227648744673592, -0.0027251565399959575, -0.0005714609416783087, -0.002974427179051827, -0.002954457775705429, -0.0025350487656832787, -0.002752787231911964, -0.0008213959937226449, -0.002506795285279442, -0.0016902106452632566, -0.0028060323693068, -0.0023197033296311494, -0.002676817451975706, -0.002509153068690429, 0.0025734179193738437, -0.0950565740913364, 0.011177902947995208, -0.0016553053879397768]]
sample6 = [[0.0004502229718805988, -0.0016156034055284246, -0.002171585213867156, -0.00148808849988856, -0.0019421206495759881, -0.0011718544708790193, -0.0014269362644221428, 0.00018934827890646977, -0.0019332864968972282, -8.06292081673144e-05, -0.0017800639459125923, -0.0017147996924286807, -0.0020103741220956757, -0.0021514436863000453, -0.0006633763226090987, -0.0015209003702047323, -0.0006304711340572737, -0.0020163115519833304, -0.0016368475570171137, -0.0024962591586122516, -0.0010639395066337647, -0.0054882827067305965, 0.030275118513399257, 0.0023903828449339643, -0.0011131512573605044], [0.015595126938272948, 0.0007051592870392278, 0.0015954540973178962, 0.002029726211985696, -0.0011434430809172196, 0.0016167141350222074, 0.0005049339087983955, -0.00272946866542027, 0.003916914715722364, 0.0029495255252593726, 0.0052721250841822635, 0.003481555978550075, 0.0026079976152730017, 0.005584726354572023, 0.003238297104412774, 0.0006873442425950339, 0.0033252328956971055, 0.0023198388123876115, 0.0007995862123314528, -0.0011581818106803734, -0.0008668689763601068, -0.023386226079927422, 0.06252208514786367, -0.014926069641097257, 0.0016587383715288768], [0.018878915687281242, 0.00020741558513020933, 0.002412241138991565, 0.0010399097330630357, -0.0011531387406882594, 9.46992214657648e-05, 0.002549381930621854, -0.002293724708416267, 0.004958498495438586, 0.0024971601871575278, 0.0058946099235549654, 0.005288143276755871, 0.006487749162978727, 0.005507792849353751, 0.0021005204099278684, 0.0036930656053224516, 0.0021717002027341467, 0.005423916270051056, -0.0006553045558487887, 0.00618633895803243, 0.0048516883340360435, -0.02336750459255019, 0.026944148332607477, 0.0029079657271681306, 0.002333855163263251], [-0.005939303558834256, 0.00336438278426819, -0.0023181343672649623, 0.0036630800180476207, 0.006817011828552724, 0.0022990967657447858, 0.0016548496325647147, 0.002280254811248716, 0.001115908976474221, -0.002251293024013791, -0.0016594546546571806, 0.0013406469539333507, 0.003678676023842889, 0.003690368037676163, -5.0962597736524635e-05, 0.003413540496318477, -9.57666796034191e-06, 0.0011554572077151987, 0.004196672897114126, 0.008759233993811321, 0.002923222261665054, -0.02111006180617856, -0.059402909563502145, 0.03511743519692408, 0.0004954535742921632], [0.0024146770208402966, 0.006247429281666467, -0.001682960416782317, 0.002447876784048966, 0.010796259232469551, 0.008544817651500747, 0.004996339435309618, -0.001045610711073112, 0.004914968897164325, 0.0012014370880243548, 0.003254456160124532, 0.0063532050466185925, 0.004711947247092733, 0.002912973968365522, 0.0036687368559980295, 0.0084020863958512, 0.003761633402238712, 0.006444333998784819, 0.00520215791646693, 0.00832734885283936, 0.014651754698085058, -0.018130696962085666, 0.02459759958652974, 0.004019299435502039, 0.0027233992038972273], [0.0073259114944286404, 0.004115858378957751, -0.0004613737121383539, 0.0026529396773511934, 0.002376031176145125, 0.00687710262775108, 0.009631346103024829, -0.0021779053052002327, 0.004367666955979146, 0.00237692287198096, 0.005247542815293592, 0.0008738498002588552, 0.004917511349205558, 0.002571221122791517, 0.002919796185489556, 0.0084221713156166, 0.0030023213573455443, 0.007015382222564133, 0.009765945269452042, 0.0033520763702274635, 0.013228261070887015, -0.009674243111491404, 0.045631217042752734, 0.0005792751377814642, 0.0020885105219305695], [-0.0006440645315227548, 0.0006313004136996824, -0.002443770765667715, -0.0002064431309466818, -9.056661468523019e-05, 0.0030664298325155217, 0.0014692142772532943, -0.0003235896837669248, -0.00031309698164147374, 0.0004518746881698849, -6.54385527947237e-05, 0.0005487838905861282, -0.002303559634527481, -0.00017689021643358063, 0.0004803754457665818, 0.0002817847975173081, 0.0005291193759705699, -0.0009083074505750943, 0.0024059185131466458, 0.0029053407713998365, -0.00012440214536572387, -0.0018569931422423075, -0.05648325033218629, -0.006635961386022534, -0.00015726008843284101], [0.003132811961230139, -0.00044786399695753357, -0.0015043364679486236, -0.0011844148115453146, 0.0005611479945235635, 0.0006552863918007411, -0.0013408363486289206, -0.0009678579841994407, -0.0016406485506803828, 0.0011207184962568834, -0.002500442606681958, -0.0020282395147337997, -0.0005486192083272374, 0.0004341333299461626, -0.00019593418805315848, -0.0017126003837440924, -0.00015655583337274108, -0.0019991646476217903, -0.0018048039536869905, -0.0025330109129047757, -0.0017699651786049102, -0.0045422234455558515, 0.018362336917577503, -0.005093884581642038, -0.0004019300628611873], [2.3824811221306974e-05, -0.002319748044568082, -0.0025823880349998725, -0.002783851791608968, -0.0022166049523122885, -0.002687251036278508, -0.002823180181780821, -0.0007888833906721222, -0.002613949562187715, -0.0006548539641757643, -0.002792647692177733, -0.0028585439168244972, -0.0024757222921655123, -0.0028139683068846674, -0.0008369388514929812, -0.002625417013511025, -0.0016996655029697274, -0.0028014114010998705, -0.002669282651060729, -0.002850684901063307, -0.0025935227184212275, 0.01695269229263564, -0.036413909884155424, -0.00914955310891357, -0.0017204170022224721]]
sample7 = [[0.0025283888334103667, -0.0020067326573674823, -0.0016546765221436908, -0.001579998026332248, -0.002460682453579401, -0.001980518531909539, -0.0019435596299912255, -0.00012727350289098419, -0.001898134964991011, 0.00024807005907667717, -0.0017602347343760344, -0.00283463585935258, -0.0016473053022769686, -0.0017238407326889123, -0.0006784396122115412, -0.0019775468326784862, -0.0006457430209786812, -0.0016598853403207903, -0.0010594695651977562, -0.002469479972999133, -0.0019007051443404156, 0.029092205898880685, 0.10287994452092558, 0.015852566264225654, -0.0010355342422257085], [0.014233846945412097, 0.0004635107517971179, 0.0012568586689139967, 0.0013108755992105282, 0.0014595031735624548, -0.0013921187055257794, 0.000891366076698992, -0.0033520701536590854, 0.00355556582454273, 0.003595876044188712, 0.005297001240189389, 0.0014810648406279106, 0.0016284808464054543, 0.005500150352207911, 0.0024910243179236563, 0.001672836568284209, 0.0025676118317791347, 0.002070996320060622, 0.0021408880494208377, -0.0016074748346690093, -0.0009315290389643709, -0.03578280899632601, 0.07111352876621571, -0.012166854765875321, 0.0015698859081574828], [0.017522085848466977, 0.0008483945988897906, 0.002074752611316223, 0.002137004032453639, 0.0006556313672692123, -0.002892699829987504, 0.0029402281352195994, -0.002648820595231281, 0.005226471682695995, 0.002865801147785174, 0.005649283188118962, 0.005713765266654052, 0.008381098698471893, 0.0023257677025860656, 0.0031616696250117765, 0.0035917774429651624, 0.0032475442744616233, 0.0037629897860987378, 0.0004036608763734057, 0.0024516819419402383, 0.004598331822495095, -0.021275262292250366, 0.01967901269212264, 0.005566015830113124, 0.002654193518517682], [-0.005726316038095513, 0.003623914435845885, -0.002371111419162757, 0.005867697241525115, 0.0035267849446493625, 0.0033995706707325457, 0.001065410385304676, 0.002512468766956296, 0.0016603906743393171, -0.0024923647426163304, -0.0009400960206195457, 0.0032971013195299908, 0.005988218331148003, 0.0006972757726573625, 0.0004321707346061494, 0.0041267553617563915, 0.0004802471231392978, 0.0018934814883649626, 0.004931892594853513, 0.011800839631585389, 0.0020892664441940433, -0.012425512166445284, -0.05535831136911384, 0.027510185557995028, 0.0009085012871946587], [-0.011358649624021382, 0.003312554297112038, -0.0009701634779296402, 0.003931290978144337, 0.004890811204264481, 0.0034264022119847677, -0.0002329668750996113, 0.0006076213991131151, 0.003051784159273614, -0.0005148572872946481, 0.0006478816541962314, 0.00417234660686997, 0.0037240708513855787, 0.008976189475879252, 0.000771298135280971, 0.004954401128118668, 0.0008240707799729942, 0.0004127983078549396, 0.004564908257458041, 0.0064543739218437925, 0.007519148076592612, -0.012845584825562018, -0.03382128513597866, -0.006375069299579899, 0.0011543674782948743], [0.012754485531826716, 0.004807598612174422, 0.000888892479574474, 1.4375920544698659e-05, 0.006309155833214012, 0.008640990710196507, 0.009236884513209604, -0.002256408636485805, 0.0031603495149760455, 0.0024584206998413535, 0.0036316625487352165, 0.0019812642909589127, 0.00410509115311981, 0.0017336765278721728, 0.004352690423750986, 0.007710656731703412, 0.004455058399161216, 0.00882365416445438, 0.009785257595000768, 0.005282337262491334, 0.013862244278712627, -0.011371637862406928, 0.028778585938483998, -0.009295208652867757, 0.0024033626349421067], [0.012934459236846878, 0.00449503106980388, 0.0009336579018772523, 0.003023317426509899, 0.0031377785186369597, 0.008695229406284824, 0.00678788457581331, -0.0014271650698427232, 0.0008389704437359737, 0.001597545774638822, 0.00201634940997963, -0.0013191339949840987, 0.0005889025101592023, 0.002219212406236325, 0.0029840589396845853, 0.006130913240141659, 0.0030674740259343187, 0.0050938393378215496, 0.006071634980365863, 0.001526064494914956, 0.007717080303590388, -0.030371428948743732, 0.030278822255787402, -0.005268658557245956, 0.0012971087701191474], [0.00011178853585717654, -0.0010150632892958348, -0.0022557650691893195, -0.0020338961836589694, 5.744305193107983e-05, -0.00158863306218865, 0.001383504910813707, -0.0003736012982616635, -0.0015509326902740043, 0.0005037939874195672, -0.001464169805128687, -0.0013338478381826576, -0.002335705136028522, -0.0008085846312773812, -0.0010287651581200354, -0.0021121150738394076, -0.0010009198956188264, -0.0028109354376085064, -0.0027320656529979405, -0.0013936815062581835, -0.0017726928000722363, -0.02408519751871006, -0.039139633752851, 0.0022952185361823367, -0.0008061795423538081], [-0.001995188754924402, -0.001496771822070626, -0.0028837053688184726, -0.0016198071676576955, -0.002241438142101864, -0.0022723189876123944, -0.0024989432848226793, -0.0007658337087514801, -0.002775771078096652, -0.0006692113091085945, -0.00282892227809862, -0.0030048800532951154, -0.002780773075144872, -0.0029250085530857003, -0.0011703498089019613, -0.002302859406724552, -0.0019024823341252236, -0.0027752855726824624, -0.0020852119785253155, -0.002236886038736055, -0.002432420554552727, 0.0028323872396246444, -0.06580481892998477, 0.011899325621451531, -0.001689574681756591]]
sample8 = [[0.001977367372330477, -0.0022334017721634927, -0.0017917338128205244, -0.0017698877216192213, -0.00252936110809962, -0.0025894029745356976, -0.0026046397981456344, -0.00028855765578044085, -0.002259194471243027, 0.0004155063692757837, -0.0019306021879014566, -0.0026281222262135437, -0.002723185376099386, -0.0026898697087431394, -0.0007663831497302638, -0.002122814709800634, -0.000734904405769207, -0.0016272459492257779, -0.0016777966745450401, -0.0022205285378056505, -0.002003172609492194, 0.04515360166193284, 0.10582275277836052, 0.027860364387140804, -0.0010131908683344195], [0.012649250544529677, 0.0006403588266761281, 0.0008627170521871694, 0.0009258946215966352, 0.0025208645896187968, -0.00023169488488423566, -0.0004461273074632714, -0.0030270861083448704, 0.0035032814215637175, 0.0032584955362705754, 0.004808356783338604, 0.0024392013708922195, -0.0006984016525102104, 0.0052483957898061175, 0.0021215151777233166, 0.000758548530627158, 0.0021929857073068864, 0.001847990840898234, 0.003294324209362745, -0.0025560519839456725, -0.0009849238879196833, -0.03499020829572827, 0.07212340214994352, -0.017371356438290474, 0.0011990551759617511], [0.017273941253612677, 0.0007390557771802384, 0.0020130308304618463, 0.0017392620487197371, 0.0011637576029229573, 4.842835187112154e-05, 0.0014189004309832825, -0.0021699056267276834, 0.005543974824996414, 0.0023686180470975076, 0.006293605051615438, 0.005804999118791365, 0.00783946844066664, 0.0037500335910630915, 0.0030212017770248427, 0.003299049504109113, 0.0031051312194671768, 0.004824325929489861, 0.0025056884378382507, 0.002160778266092963, 0.0032065028050907887, -0.0289903636782423, 0.018298976736102736, 0.0052404154615536295, 0.0024159830542386054], [-0.003914528662687534, 0.004582144919540841, -0.002821762957252136, 0.004782674542373175, 0.0067987492674227, 0.005138690023048796, 0.003680426593131769, 0.002222436548118385, 0.0026850934675936903, -0.002191269292808786, -0.0020803649728819034, 0.004363634257081145, 0.00947793229451459, 0.0011773283187368094, 0.0023267910514684254, 0.005468407485506782, 0.002401104253405882, 0.005335093783580445, 0.005232657703001723, 0.0125886734905121, 0.0017227063372447773, -0.019197191361992334, -0.06809047258629344, 0.026419384855717615, 0.001583929752033035], [-0.006644495052282548, 0.0048078885830937215, -0.0021427298824542333, 0.0031198482785203705, 0.00999279410486014, 0.002452745716406155, 0.006693976808433229, 0.0007472799767693932, 0.0037027526599234316, -0.0006598431182736524, -0.0005154969326235159, 0.00450235676745412, 0.0009634478396310731, 0.012974988222706391, 0.002279820219395822, 0.005166386016249105, 0.0023534829664925046, -0.0002712932606225907, 0.012449424416705105, 0.008583755599298765, 0.007156771995934546, -0.020413904832808426, -0.0722075253879328, 0.007675151842758878, 0.0018502911415845713], [0.01762289250001778, 0.004203772924199306, 0.0020998265649090275, -0.0011768197934449553, 0.009463017999742753, 0.004465355547731982, 0.005709117612728778, -0.0023955220023161744, 0.004199988379544223, 0.002602840521979615, 0.00417798491972817, 0.003730565049137728, 0.005431580253602968, 0.0053641649282261256, 0.004229277789049868, 0.007417890349682851, 0.004329936739047686, 0.006607535250679799, 0.0012965654028018372, 0.007708521638947686, 0.012795539854381168, -0.0167635342691674, 0.011782431493114988, -0.006967250342908943, 0.0029574628820681756], [0.012087583207431864, 0.004074672001864416, 0.0007230117794861172, 0.002333727553699876, 0.002964806174886498, 0.00876003983424261, 0.0060726068071011545, -0.0014657842755909463, 0.0020279987355989126, 0.0016376381035964887, 0.0038325235696482444, -0.00029953704106980435, 0.0013207624371044712, 0.0005967560492903262, 0.0028332847434039163, 0.006559278289158452, 0.002914611899729754, 0.005615633050516868, 0.004307310150503135, 0.005475695430915178, 0.010809119033195601, -0.025505377185464976, 0.029611512596407315, -0.009292793719082131, 0.0015135249034562434], [6.903427761107335e-05, -0.0006429887382667307, -0.002266399469505824, -0.0016249580776866567, -0.0003948331789078573, 0.0010815859706338733, -0.0012645087812005068, -0.00016601967177853896, -0.0006008991733160129, 0.0002882941941616041, 0.00018023198240703174, -0.0021972459491259528, 0.00018691632174245622, -0.0019196921569370113, -0.0013005634142846793, -0.0017275657472504689, -0.0012764820299954482, -0.0027244609360284363, -0.0001388417737390766, -0.0013024039262374144, -0.0008880570213288285, -0.022923080684551938, -0.0048597564462615215, 0.0025193388558630886, -0.0007139673904393436], [0.0012567751198894386, -0.0014144403834033042, -0.0019709689765630245, -0.002754901662268408, -0.00040671735861867123, -0.0010685172944501194, -0.0007966704371274486, -0.0011767502914061456, -0.0014655594391495325, 0.0013375789659376305, -0.0020453578278819204, -0.0003887524682445495, -0.0015494722859005902, -0.0019552010473551733, -0.0014102186224975225, -0.0020421900302221097, -0.0013876557499708253, -0.0026938936850765174, -0.0014304933111129916, -0.0017730134553240655, -0.0016344257478396144, -0.014969231535889999, -0.005247785902749733, 0.007136679126300961, -0.0005273869538717846], [0.00010337131480406393, -0.002550896716571234, -0.002414187617791389, -0.0028456692250104013, -0.002275408630192338, -0.0030245806094632835, -0.0025718367370716217, -0.0010340987610062478, -0.0024963736726125417, 0.000343686747187423, -0.0026901661956728194, -0.0023254915232176075, -0.0026649241521767533, -0.0028432290983394, -0.0013335943174954137, -0.0026301532851752706, -0.0016558778790497217, -0.0028080146720562914, -0.0022695110253211346, -0.002855663706819314, -0.002706400564893073, -0.00017992408680345508, -0.04068735168855553, 0.024467295861085727, -0.0012079223259253606]]
sample9 = [[0.017384327567596752, -0.00038213421161916464, 0.002040487563440648, 0.0006199856155318895, -0.0011274131252662525, -0.002571882172427863, 0.0020296674620381015, -0.001955673320763256, 0.004985623615778575, 0.00214621388529052, 0.0069498450352333055, 0.00497186337092835, 0.002810790482699285, 0.0048755789974965, 0.003486969753127313, 0.0013396339058168035, 0.0035773491778536655, 0.0004690689405044505, -0.000691486283022591, 0.002152931697649469, 0.0009045507678496276, -0.025757712977832328, 0.017031874289588963, 0.005526647262948762, 0.0018480878249379513], [0.009599423066568354, 0.001951030203032952, 0.00010412392889584989, 0.0018451148010099254, 0.002340465483638871, 0.0005448667481454992, -0.00012523248584678692, -0.001158435910677159, 0.0044619627124915795, 0.0013185659861878784, 0.002562382362306182, 0.0077375939187609415, 0.005334130346392195, 0.0036095590148723994, 0.001558445740678137, 0.003096460435386101, 0.0016221188516327915, 0.004507575623922629, 0.0028079827009120464, 0.006747247400507751, 0.0026365156158892683, -0.0225459720677888, -0.013897675734102088, 0.008948143906231436, 0.001859857510710745], [-0.006555606257685964, 0.004201047438221682, -0.002164839470227932, 0.00530785994312255, 0.006641271972624684, 0.0028698067697916583, 0.00555699493446551, 0.001082247932200181, 0.0006583562272447956, -0.0010075883709068166, -0.00013958295339202713, 0.0008339025269868432, 0.0045466568807781, 0.0005558605339102007, 3.269550128237304e-05, 0.0030914355719290024, 7.523993332636258e-05, 0.0027544159117760215, 0.007159613801685732, 0.009177337789764177, 0.0003091147043861774, -0.0373936686263127, -0.08129356299792896, 0.03289819618686216, 0.0006482582720660634], [0.0019576853173513603, 0.007097940192649162, -0.001796629391887633, 0.003934718177635379, 0.013167477014658136, 0.005495125090069663, 0.0067932415796011164, -0.00216842743388185, 0.004197808809646829, 0.002367083468830301, 0.003942862625659727, 0.005851741701947433, -0.0008857298663788782, 0.0068424863973912545, 0.0058987962287765, 0.0051654617776406425, 0.006022574768165561, 0.005526918586855329, 0.00022011155345376157, 0.01013155434051848, 0.002804335721909002, -0.019169113610390278, 0.011382257257849773, -0.0013718136300127591, 0.00300226329467059], [0.008627898944390264, 0.005126916072157563, -0.0001375263032964913, 0.0008894904948925887, 0.005027560979884948, 0.010075780577320347, 0.009202727498631496, -0.0021170683839813235, 0.0037975349181963267, 0.0023137653364743594, 0.005401863892475499, 0.0014802938978263627, 0.003837288218397853, 0.002712723637350812, 0.004055678605076816, 0.0048332688809481685, 0.004153933543380838, 0.006156572173091346, 0.0033950977949033655, 0.004164193917764645, 0.007913003731462686, -0.009411916656975, 0.041422635741069865, -0.012115286422297094, 0.0019063171431144372], [0.006234542175710148, -7.820112441362078e-05, -0.0007328334147391054, -0.002383514209210702, 0.002373112429511654, -0.0017577551369479894, 0.0017612540389770797, 0.00016197746526001584, -0.0004048003891878361, -5.2214339365847915e-05, 3.197947740864058e-05, -0.0002456413436447556, -0.0005158449941377389, -0.0001814029980693513, -0.0010577312923548677, -0.0009565227594620372, -0.0010302871545815, -0.001931171018103322, 0.00033338462808230496, -0.0015101494665800059, -0.0023953519228967317, -0.01641547136377696, -0.05860180465889028, -0.0006621349093751698, -0.000697168607285188], [0.0038856232804833613, -0.000754427172094934, -0.002006053711142825, -0.0009567821761597795, -0.0014027068045527839, -0.002383433710053106, -0.0026112244463370677, -0.001427579558974929, -0.0009777049364274322, -0.00025701848743592796, -0.0014297608025499104, -0.0019746904905570614, -0.0019795580253572846, -0.0018188325510388604, -0.0010506352327130234, -0.001474868046894706, -0.0018296588997232758, -0.0027062652150331833, -0.00047898913047851154, -0.0026133474142564224, -0.0019556269643267138, -0.03806253831639386, -0.0019991792001937394, -0.002410863953684941, -0.0014145084643234173]]

trainingsSet = [sample1, sample2, sample3, sample4, sample5, sample6, sample7, sample8, sample9]

model = HiddenMarkovModel('Test')

# Simple model with 3 states and a simple left to right structure will created.
# The chances for moving to the next state will be 0.6
# As Distribution i use a Multivariate Gaussian Distribution initialized with parameters calculated
# by the first 3 Feature Vectors of every sample in __genMultiGaussianDistWithCovMatrix

states = []

# First State
mgd = __genMultiGaussianDistWithCovMatrix(0)
state = State(mgd, 'Q0')
states.append(state)

# Second State
mgd = __genMultiGaussianDistWithCovMatrix(1)
state = State(mgd, 'Q1')
states.append(state)

# Third State
mgd = __genMultiGaussianDistWithCovMatrix(2)
state = State(mgd, 'Q2')
states.append(state)

# Add States
model.add_states(states)

# Add Transitions
model.add_transition(model.start, states[0], 1.0)
model.add_transition(states[0], states[0], 0.4)
model.add_transition(states[0], states[1], 0.6)
model.add_transition(states[1], states[1], 0.4)
model.add_transition(states[1], states[2], 0.6)
model.add_transition(states[2], model.end, 1)

model.bake()

model.train(trainingsSet)
```

**Comment by Narsail** [comment]
I extended the sample code. It goes through the following cases:

- Building a 3 state model with a Multivariate Independent Component Distribution (MICD) and a Multivariate Gaussian Distribution (MGD)
- Furthermore there is a out commented extra Distribution test where one MGD is tested with every Featurevector. The log_probability is always 'inf'.

For the MGD case:

i have no idea what is happening here. I checked the calculation of my cov matrix more than once and still can't find an error. But i guess the problem lies there because the log_prob with a MICD isn't producing 'inf's. And the difference is the cov matrix.

For the MICD case:
The log_probability is producing logical results but i get the mentioned Overflow Exception when training a HMM. The funny part is, that it is always producing different Training improvements. Sometimes it is directly 'nan', sometimes  i get:

<img width="720" alt="screen shot 2016-01-02 at 11 04 18 2" src="https://cloud.githubusercontent.com/assets/7859096/12074103/cbbefece-b141-11e5-8c97-6e135ee13c35.png">

**Comment by jmschrei** [comment]
sorry for the delay. IndependentComponentDistribution should work now. There was an error in passing the weight array around.

**Comment by jmschrei** [comment]
I'm actually not following how you're initializing these distributions. It looks like you're initializing them using different time steps in each sample?

**Comment by jmschrei** [comment]
The reason the MultivariateGaussian one isn't working is because the determinant of the covariance matrix is 0, making all log probabilities under that equal to infinity. I'm not sure what fix I should implement on my end, but you need an invertiable covariance matrix for things to work right.

**Comment by Narsail** [comment]
Okay, thanks for the hint. I will look into that. 

At the moment i'm playing with your update. It seems to be working but there is an output of the following format even with verbose=False: 
´´´
hmm:  -inf -6970.26859321 57.4233855572
hmm:  -inf -inf 57.4233855572
hmm:  -inf -inf 57.4233855572
´´´

**Comment by jmschrei** [comment]
That was a mistake on my part which I fixed a few days ago, pulling the most recent code should solve that. Is the other problem solved?

**Comment by jmschrei** [comment]
Closing for now. Please re-open if still an issue.
