### ISSUE TITLE
ConditionalProbabilityTable.marginal() call fails with KeyError

### ISSUE THREAD

**Issue by nknezek** [jmschrei/pomegranate#593]
given the code snippet below, the calling `marginal()` on most of the nodes in the model throws an error. 
```python
import math
from pomegranate import *

friend = DiscreteDistribution( { True: 0.5, False: 0.5 } )

guest = ConditionalProbabilityTable(
	[[ True, 'A', 0.50 ],
	 [ True, 'B', 0.25 ],
	 [ True, 'C', 0.25 ],
	 [ False, 'A', 0.0 ],
	 [ False, 'B', 0.7 ],
	 [ False, 'C', 0.3 ]], [friend] )

remaining = DiscreteDistribution( { 0: 0.1, 1: 0.7, 2: 0.2, } )

randomize = ConditionalProbabilityTable(
	[[ 0, True , 0.05 ],
     [ 0, False, 0.95 ],
     [ 1, True , 0.8 ],
     [ 1, False, 0.2 ],
     [ 2, True , 0.5 ],
     [ 2, False, 0.5 ]], [remaining] )

prize = ConditionalProbabilityTable(
	[[ True, True, 'A', 0.3 ],
	 [ True, True, 'B', 0.4 ],
	 [ True, True, 'C', 0.3 ],
	 [ True, False, 'A', 0.2 ],
	 [ True, False, 'B', 0.4 ],
	 [ True, False, 'C', 0.4 ],
	 [ False, True, 'A', 0.1 ],
	 [ False, True, 'B', 0.9 ],
	 [ False, True, 'C', 0.0 ],
	 [ False, False, 'A', 0.0 ],
	 [ False, False, 'B', 0.4 ],
	 [ False, False, 'C', 0.6]], [randomize, friend] )

monty = ConditionalProbabilityTable(
	[[ 'A', 'A', 'A', 0.0 ],
	 [ 'A', 'A', 'B', 0.5 ],
	 [ 'A', 'A', 'C', 0.5 ],
	 [ 'A', 'B', 'A', 0.0 ],
	 [ 'A', 'B', 'B', 0.0 ],
	 [ 'A', 'B', 'C', 1.0 ],
	 [ 'A', 'C', 'A', 0.0 ],
	 [ 'A', 'C', 'B', 1.0 ],
	 [ 'A', 'C', 'C', 0.0 ],
	 [ 'B', 'A', 'A', 0.0 ],
	 [ 'B', 'A', 'B', 0.0 ],
	 [ 'B', 'A', 'C', 1.0 ],
	 [ 'B', 'B', 'A', 0.5 ],
	 [ 'B', 'B', 'B', 0.0 ],
	 [ 'B', 'B', 'C', 0.5 ],
	 [ 'B', 'C', 'A', 1.0 ],
	 [ 'B', 'C', 'B', 0.0 ],
	 [ 'B', 'C', 'C', 0.0 ],
	 [ 'C', 'A', 'A', 0.0 ],
	 [ 'C', 'A', 'B', 1.0 ],
	 [ 'C', 'A', 'C', 0.0 ],
	 [ 'C', 'B', 'A', 1.0 ],
	 [ 'C', 'B', 'B', 0.0 ],
	 [ 'C', 'B', 'C', 0.0 ],
	 [ 'C', 'C', 'A', 0.5 ],
	 [ 'C', 'C', 'B', 0.5 ],
	 [ 'C', 'C', 'C', 0.0 ]], [guest, prize] )

s0 = State( friend, name="friend")
s1 = State( guest, name="guest" )
s2 = State( prize, name="prize" )
s3 = State( monty, name="monty" )
s4 = State( remaining, name="remaining" )
s5 = State( randomize, name="randomize" )

network = BayesianNetwork( "test" )
network.add_states(s0, s1, s2, s3, s4, s5)

network.add_transition( s0, s1 )
network.add_transition( s1, s3 )
network.add_transition( s2, s3 )
network.add_transition( s4, s5 )
network.add_transition( s5, s2 )
network.add_transition( s0, s2 )

network.bake()
```
calling
```python
guest.marginal()
```
gives 
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-77-f282b0d34b0b> in <module>
     86 
     87 print(network.states[1].distribution == guest)
---> 88 guest.marginal()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.marginal()

pomegranate/distributions/JointProbabilityTable.pyx in pomegranate.distributions.JointProbabilityTable.JointProbabilityTable.marginal()

KeyError: 'A'
```

Similarly, a call to 
```python
prize.marginal()
```

raises a `TypeError`

```
TypeError                                 Traceback (most recent call last)
<ipython-input-33-ff01076ba5e3> in <module>
----> 1 prize.marginal()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.marginal()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.joint()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.log_probability()

TypeError: 'bool' object is not iterable
```

I believe this is due to how the keys of `self.keymap` are being iterated over in the call to `joint()`:

```python
cdef class ConditionalProbabilityTable(MultivariateDistribution):
        ...
	def joint(self, neighbor_values=None):
		"""
		This will turn a conditional probability table into a joint
		probability table. If the data is already a joint, it will likely
		mess up the data. It does so by scaling the parameters the probabilities
		by the parent distributions.
		"""

		neighbor_values = neighbor_values or self.parents+[None]
		if isinstance(neighbor_values, dict):
			neighbor_values = [neighbor_values.get(p, None) for p in self.parents + [self]]

		table, total = [], 0
		for key, idx in self.keymap.items():
			scaled_val = self.values[idx]

			for j, k in enumerate(key):
				if neighbor_values[j] is not None:
					scaled_val += neighbor_values[j].log_probability(k)

			scaled_val = cexp(scaled_val)
			total += scaled_val
			table.append(key + (scaled_val,))

		table = [row[:-1] + (row[-1] / total if total > 0 else 1. / self.n,) for row in table]
		return JointProbabilityTable(table, self.parents)
```

in that `log_probability()` expects a tuple of state values, but is being passed a single state value as a string instead. 

I'm trying to compute individual node probabilities given specific neighbor values, and cannot figure out how to do it with this error. Any help would be appreciated!

**Comment by jmschrei** [comment]
Can you try making all keys strings? I haven't extensively tested mixed type tables.

**Comment by nknezek** [comment]
I've updated the code to use only strings for keys:
```python
import math
from pomegranate import *

friend = DiscreteDistribution( { "true": 0.5, "false": 0.5 } )

guest = ConditionalProbabilityTable(
	[[ "true", 'A', 0.50 ],
	 [ "true", 'B', 0.25 ],
	 [ "true", 'C', 0.25 ],
	 [ "false", 'A', 0.0 ],
	 [ "false", 'B', 0.7 ],
	 [ "false", 'C', 0.3 ]], [friend] )

remaining = DiscreteDistribution( { "0": 0.1, "1": 0.7, "2": 0.2, } )

randomize = ConditionalProbabilityTable(
	[[ "0", "true" , 0.05 ],
     [ "0", "false", 0.95 ],
     [ "1", "true" , 0.8 ],
     [ "1", "false", 0.2 ],
     [ "2", "true" , 0.5 ],
     [ "2", "false", 0.5 ]], [remaining] )

prize = ConditionalProbabilityTable(
	[[ "true", "true", 'A', 0.3 ],
	 [ "true", "true", 'B', 0.4 ],
	 [ "true", "true", 'C', 0.3 ],
	 [ "true", "false", 'A', 0.2 ],
	 [ "true", "false", 'B', 0.4 ],
	 [ "true", "false", 'C', 0.4 ],
	 [ "false", "true", 'A', 0.1 ],
	 [ "false", "true", 'B', 0.9 ],
	 [ "false", "true", 'C', 0.0 ],
	 [ "false", "false", 'A', 0.0 ],
	 [ "false", "false", 'B', 0.4 ],
	 [ "false", "false", 'C', 0.6]], [randomize, friend] )

monty = ConditionalProbabilityTable(
	[[ 'A', 'A', 'A', 0.0 ],
	 [ 'A', 'A', 'B', 0.5 ],
	 [ 'A', 'A', 'C', 0.5 ],
	 [ 'A', 'B', 'A', 0.0 ],
	 [ 'A', 'B', 'B', 0.0 ],
	 [ 'A', 'B', 'C', 1.0 ],
	 [ 'A', 'C', 'A', 0.0 ],
	 [ 'A', 'C', 'B', 1.0 ],
	 [ 'A', 'C', 'C', 0.0 ],
	 [ 'B', 'A', 'A', 0.0 ],
	 [ 'B', 'A', 'B', 0.0 ],
	 [ 'B', 'A', 'C', 1.0 ],
	 [ 'B', 'B', 'A', 0.5 ],
	 [ 'B', 'B', 'B', 0.0 ],
	 [ 'B', 'B', 'C', 0.5 ],
	 [ 'B', 'C', 'A', 1.0 ],
	 [ 'B', 'C', 'B', 0.0 ],
	 [ 'B', 'C', 'C', 0.0 ],
	 [ 'C', 'A', 'A', 0.0 ],
	 [ 'C', 'A', 'B', 1.0 ],
	 [ 'C', 'A', 'C', 0.0 ],
	 [ 'C', 'B', 'A', 1.0 ],
	 [ 'C', 'B', 'B', 0.0 ],
	 [ 'C', 'B', 'C', 0.0 ],
	 [ 'C', 'C', 'A', 0.5 ],
	 [ 'C', 'C', 'B', 0.5 ],
	 [ 'C', 'C', 'C', 0.0 ]], [guest, prize] )

s0 = State( friend, name="friend")
s1 = State( guest, name="guest" )
s2 = State( prize, name="prize" )
s3 = State( monty, name="monty" )
s4 = State( remaining, name="remaining" )
s5 = State( randomize, name="randomize" )

network = BayesianNetwork( "test" )
network.add_states(s0, s1, s2, s3, s4, s5)

network.add_transition( s0, s1 )
network.add_transition( s1, s3 )
network.add_transition( s2, s3 )
network.add_transition( s4, s5 )
network.add_transition( s5, s2 )
network.add_transition( s0, s2 )

network.bake()
```

but 
```python
guest.marginal()
```
 still gives
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-3457a515ed4b> in <module>
----> 1 guest.marginal()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.marginal()

pomegranate/distributions/JointProbabilityTable.pyx in pomegranate.distributions.JointProbabilityTable.JointProbabilityTable.marginal()

KeyError: 'C'
```

and 
```python
prize.marginal()
```
gives
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-ff01076ba5e3> in <module>
----> 1 prize.marginal()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.marginal()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.joint()

pomegranate/distributions/ConditionalProbabilityTable.pyx in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.log_probability()

KeyError: ('t', 'r', 'u', 'e')
```

**Comment by mazzarellaf** [comment]
Hello,
Any updates on this issue? I got the same problem. 

Many thanks!

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
